### ISSUE TITLE
ubuntu 14.04 has the error

### ISSUE THREAD

**Issue by victorchoy** [xavi-/node-copy-paste#38]
Error: A synchronous version of paste is not supported on this platform.
    at Object.exports.paste (/home/victor/Documents/share-clipboard/node-copy-paste/index.js:97:9)
    at checkAndPushText (/home/victor/Documents/share-clipboard/share-clipboard.js:18:33)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by xavi-** [comment]
This is because the module couldn't find or install an exec-sync that works.  If you can try upgrading to the latest version of node.
