### ISSUE TITLE
Bundle error: Error: Cannot find module './platform/openbsd' 

### ISSUE THREAD

**Issue by jcalfee** [xavi-/node-copy-paste#59]
I'm trying to package my program for use on another Linux computer running node.  I do not have the `openbsd` folder and I get this error:

```bash
$ echo 'require("copy-paste").copy(String(Math.random()), () =>{})' > test.js
$ browserify --bare test.js -o out.js
Error: Cannot find module './platform/openbsd' from '/home/jcalfee/eosjs/trez/node_modules/copy-paste'
    at /home/jcalfee/eosjs/trez/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/jcalfee/eosjs/trez/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/jcalfee/eosjs/trez/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/jcalfee/eosjs/trez/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

I did find a work around:
```bash
browserify --bare test.js -o out.js --ignore-missing
```

What is the best way to package your module for node?

**Comment by unchartedworks** [comment]
open index.js and delete the code for supporting openbsd. 
```	
case "openbsd":
	config = require("./platform/openbsd");
	break;
```

**Comment by queeniema** [comment]
I'm having the same issue when compiling with webpack. Shouldn't this work out of the box?

```
ERROR in ./node_modules/copy-paste/index.js
Module not found: Error: Can't resolve './platform/openbsd' in '/Users/queeniema/github/myExtension/node_modules/copy-paste'
 @ ./node_modules/copy-paste/index.js 34:11-40
```
